fernet_key = "u2V_6K3Xp6s9zQ8yL1mN4oP7rS0tU5wXyZ2aBcDfG="
# Supprimez les crochets [supabase] si vous voulez appeler directement st.secrets["SUPABASE_URL"]
SUPABASE_URL = "https://pgstyrsaesojmdaucbst.supabase.co"
SUPABASE_KEY = "sb_publishable_OQvsHXZ-2i85rDwmySKjhg_iWNPYIdT"
